# Generated by Django 4.1 on 2023-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=50)),
                ('Bookname', models.CharField(max_length=100)),
            ],
        ),
    ]
